<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<div style="padding:20px;margin-top:30px;height:1500px;">
<h1>Fixed Top Navigation Bar</h1>
<h2>Scroll this page to see the effect</h2>
<h2>The navigation bar will stay at the top of the page while scrolling</h2>

<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
<p>SEARCH SEARCH SEARCH SEARCH SEARCH SEARCH.</p>
</div>
</html>